version: '3.8'

services:
  frontend:
    build:
      dockerfile:  Dockerfile.ubuntu
      context: ./
    volumes:
      - type: bind
        source: /var/www/frontend
        target: /frontend
    command: >
      bash -c "npm install
      && ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url='./'"
