version: '3.8'

services:
  web:
    build: .
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /var/www/frontend:/star_burger/frontend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bilipe41
      - POSTGRES_DB=star-burgerdb
    ports:
      - 5432:5432

volumes:
  postgres_data:
