version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput
      && gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/opt/star-burger
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
  
  frontend:
    build:
      dockerfile: Dockerfile.ubuntu
      context: ./frontend
    command: >
      bash -c "npm install
      && ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./""
    volumes:
      - ./:/frontend

volumes:
  postgres_data: