version: '3.8'

services:
  web:
    build: .
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /var/www/frontend/bundles:/opt/star-burger/frontend/bundles
      - /var/www/frontend/static:/opt/star-burger/static
      - /var/www/frontend/media:/opt/star-burger/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bilipe41
      - POSTGRES_DB=star-burgerdb
    depends_on:
      - frontend

  frontend:
    build:
      dockerfile: Dockerfile.ubuntu
      context: ./frontend
    command: >
      bash -c "npm install
      && ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
      && touch new.txt"
    volumes:
      - /var/www/frontend:/frontend

volumes:
  postgres_data:
