# Generated by Django 3.2.15 on 2024-03-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
    ]
