# Generated by Django 4.1.5 on 2023-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Необработанный заказ'), (2, 'Сборка'), (3, 'Доставляется'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='статус заказа'),
        ),
    ]
