# Generated by Django 4.1.5 on 2023-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_rename_registred_at_order_registrated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Наличностью'), (2, 'Электронно')], default=2, verbose_name='Способ оплаты'),
        ),
    ]
