# Generated by Django 4.1.5 on 2023-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Наличностью'), (2, 'Электронно')], db_index=True, default=2, verbose_name='Способ оплаты'),
        ),
    ]
