# Generated by Django 4.1.5 on 2023-02-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_orderproduct_order_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooking_orders', to='foodcartapp.restaurant', verbose_name='Ресторан, готовящий заказ'),
        ),
    ]
