# Generated by Django 3.2.15 on 2024-03-13 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=11, help_text='цена одного продукта на момент оформления заказа', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена продукта'),
            preserve_default=False,
        ),
    ]
